import 'dotenv/config';
import express from 'express'; import cors from 'cors'; import bcrypt from 'bcrypt'; import jwt from 'jsonwebtoken'; import swaggerUi from 'swagger-ui-express'; import {prisma} from './lib/prisma'; import {auth,AuthRequest} from './middleware/auth';
const app=express(); app.use(cors({origin:process.env.CORS_ORIGIN?.split(',')||'*'})); app.use(express.json());
const page=(v:any)=>Math.max(1,Number(v)||1); const size=(v:any)=>Math.min(100,Math.max(1,Number(v)||10));
function token(u:any){return jwt.sign({sub:u.id,tenantId:u.tenantId,email:u.email},process.env.JWT_SECRET||'change-me',{expiresIn:'8h'});}
app.get('/api/health',(_req,res)=>res.json({status:'ok',service:'app-mobile-api'}));
app.post('/api/auth/login',async(req,res)=>{try{const {email,senha}=req.body; if(!email||!senha)return res.status(400).json({message:'email e senha são obrigatórios'}); const u=await prisma.usuario.findUnique({where:{email},include:{tenant:true}}); if(!u||!(await bcrypt.compare(senha,u.senha)))return res.status(401).json({message:'Credenciais inválidas'}); res.json({token:token(u),user:{id:u.id,nome:u.nome,email:u.email,tenantId:u.tenantId,tenant:u.tenant}});}catch(e){res.status(500).json({message:'Erro no login'});}});
app.get('/api/dashboard',auth,async(req:AuthRequest,res)=>{const tenantId=req.user!.tenantId; const [contas,receitas,despesas]=await Promise.all([prisma.conta.findMany({where:{tenantId,ativo:true},orderBy:{nome:'asc'}}),prisma.transacao.aggregate({where:{tenantId,tipo:'R',status:'A'},_sum:{valor:true}}),prisma.transacao.aggregate({where:{tenantId,tipo:'D',status:'A'},_sum:{valor:true}})]); const r=Number(receitas._sum.valor||0),d=Number(despesas._sum.valor||0); res.json({tenantId,receitas:r,despesas:d,saldo:r-d,contas});});
async function list(model:any,req:AuthRequest,res:any){const p=page(req.query.page),s=size(req.query.pageSize),where={tenantId:req.user!.tenantId}; const [items,total]=await Promise.all([model.findMany({where,skip:(p-1)*s,take:s,orderBy:{nome:'asc'}}),model.count({where})]); res.json({items,page:p,pageSize:s,total,totalPages:Math.ceil(total/s)});}
function crud(path:string,model:any){app.get('/api/'+path,auth,(req,res)=>list(model,req as AuthRequest,res)); app.post('/api/'+path,auth,async(req:AuthRequest,res)=>{try{const item=await model.create({data:{...req.body,tenantId:req.user!.tenantId}});res.status(201).json(item);}catch(e){res.status(400).json({message:'Dados inválidos'});}}); app.put('/api/'+path+'/:id',auth,async(req:AuthRequest,res)=>{try{const item=await model.updateMany({where:{id:req.params.id,tenantId:req.user!.tenantId},data:req.body}); if(!item.count)return res.status(404).json({message:'Registro não encontrado'});res.json(await model.findFirst({where:{id:req.params.id,tenantId:req.user!.tenantId}}));}catch(e){res.status(400).json({message:'Dados inválidos'});}}); app.delete('/api/'+path+'/:id',auth,async(req:AuthRequest,res)=>{try{const item=await model.deleteMany({where:{id:req.params.id,tenantId:req.user!.tenantId}});if(!item.count)return res.status(404).json({message:'Registro não encontrado'});res.status(204).send();}catch(e){res.status(400).json({message:'Não foi possível excluir'});}});}
crud('contas',prisma.conta); crud('categorias',prisma.categoria);
app.get('/api/transacoes',auth,async(req:AuthRequest,res)=>{const p=page(req.query.page),s=size(req.query.pageSize),where={tenantId:req.user!.tenantId}; const [items,total]=await Promise.all([prisma.transacao.findMany({where,skip:(p-1)*s,take:s,orderBy:{data:'desc'},include:{conta:true,categoria:true}}),prisma.transacao.count({where})]);res.json({items,page:p,pageSize:s,total,totalPages:Math.ceil(total/s)});});
app.post('/api/transacoes',auth,async(req:AuthRequest,res)=>{try{const item=await prisma.transacao.create({data:{...req.body,tenantId:req.user!.tenantId,valor:Number(req.body.valor),data:new Date(req.body.data)}});res.status(201).json(item);}catch(e){res.status(400).json({message:'Dados inválidos'});}});
app.put('/api/transacoes/:id',auth,async(req:AuthRequest,res)=>{try{const data={...req.body};if(data.valor!==undefined)data.valor=Number(data.valor);if(data.data)data.data=new Date(data.data);const r=await prisma.transacao.updateMany({where:{id:req.params.id,tenantId:req.user!.tenantId},data});if(!r.count)return res.status(404).json({message:'Registro não encontrado'});res.json(await prisma.transacao.findFirst({where:{id:req.params.id,tenantId:req.user!.tenantId}}));}catch(e){res.status(400).json({message:'Dados inválidos'});}});
app.delete('/api/transacoes/:id',auth,async(req:AuthRequest,res)=>{const r=await prisma.transacao.deleteMany({where:{id:req.params.id,tenantId:req.user!.tenantId}});if(!r.count)return res.status(404).json({message:'Registro não encontrado'});res.status(204).send();});
app.get('/api/docs',(_req,res)=>res.json({openapi:'3.0.0',info:{title:'App Mobile Finance API',version:'1.0.0'},servers:[{url:'/api'}],paths:{'/health':{get:{summary:'Health check'}},'/auth/login':{post:{summary:'Login'}},'/dashboard':{get:{summary:'Dashboard'}},'/contas':{get:{summary:'Lista contas'},post:{summary:'Cria conta'}},'/categorias':{get:{summary:'Lista categorias'},post:{summary:'Cria categoria'}},'/transacoes':{get:{summary:'Lista transações'},post:{summary:'Cria transação'}}}}}));
if(process.env.VERCEL!=='1')app.listen(Number(process.env.PORT)||3000,()=>console.log('API running on port '+(process.env.PORT||3000))); export default app;
